local_backend: true
backend:
  name: git-gateway
  branch: main
locale: pt
media_folder: public/images
public_folder: /images
collections:
  - name: files
    label: Files
    files:
      - name: file
        label: File
        file: content/file.md
        editor:
          preview: false
        fields:
          - widget: string
            name: title
            label: Title
