backend:
  name: git-gateway
  branch: main
locale: pt-BR
site_url: https://www.giomurakami.des.br
display_url: https://www.giomurakami.des.br
logo_url: https://www.giomurakami.des.br/pendente.svg
media_folder: public/images
public_folder: /images
media_library:
  name: uploadcare
  config:
    publicKey: f07c3de16a476579b849
    multiple: true
    crop: free
    locale: pt
collections:
  - name: config
    label: Configurações
    files:
      - name: about
        label: Sobre
        file: src/content/config/about.md
        extension: md
        editor:
          preview: false
        fields:
          - widget: string
            label: Título
            name: title
            default: Quem sou eu
          - widget: markdown
            label: Conteúdo
            name: body
          - widget: image
            label: Foto
            name: image
            media_library:
              config:
                multiple: false
      - name: budget
        label: Orçamento
        file: src/content/config/form-entries.json
        extension: json
        editor:
          preview: false
        fields:
          - widget: string
            label: Título
            name: title
            default: Formulário de orçamento
      - name: color
        label: Cores
        file: src/content/config/color.json
        extension: json
        editor:
          preview: false
        fields:
          - widget: color
            label: Padrão
            name: default
            allowInput: true
          - widget: color
            label: Escura
            name: dark
            allowInput: true
          - widget: color
            label: Clara
            name: light
            allowInput: true
